### ISSUE TITLE
Kernel 4.9

### ISSUE THREAD

**Issue by AndreasGocht** [tud-zih-energy/x86_adapt#1]
X86_adapt has some problems with the kernel 4.9. The branch 4_10 seems to fix them.
I tested with the current Debian testing on my machine. x86a_read works as expected. 
I would suppose to merge the branch if the patch doesn't brake x86_a for older kernels.

Best,
Andreas

**Comment by rschoene** [comment]
I guess the branch has already been merged with e6109aeb679ebc8fd7300ae0a65d6d28003225c1 . Can this be closed?
