### ISSUE TITLE
x86 node knobs listed under CPU knobs

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/x86_adapt#10]
e.g. `lo2s --list-knobs` shows the following twice

```
  Intel_PKG_C2_RESIDENCY
  Intel_PKG_C3_RESIDENCY
  Intel_PKG_C6_RESIDENCY
```

Could also be an x86_adapt issue because `Intel_PKG_C7_RESIDENCY` is listed as CPU knob but  `Intel_PKG_C7_RESIDENCY_deprecated` is listed as node knob.

**Comment by rschoene** [comment]
You're right, it should be the other way around. Fix planned for this week

**Comment by rschoene** [comment]
Pckg C7 is now deprecated for CPU, and non-deprecated for node. I pushed the changes with 8b02cb574cfad9b950bef068c24b03ea6fbb41da . The per CPU counters are deprecated (visible in the description) but remain available to allow compatibility with older software. Close, if this works for you

**Comment by tilsche** [comment]
Thanks. We track any further issues with double listing in `lo2s` in the respective issue: https://github.com/tud-zih-energy/lo2s/issues/125
